# Generated by Django 5.1.1 on 2024-09-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='nome', max_length=100)),
                ('email', models.EmailField(help_text='Informe o email', max_length=70)),
                ('tpUser', models.CharField(choices=[('E', 'EDITOR'), ('R', 'REVISOR'), ('L', 'LEITOR')], max_length=1)),
            ],
        ),
    ]
