# Generated by Django 5.1.1 on 2024-09-25 15:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VersoLivro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('A', 'Autoajuda'), ('B', 'Bibliografia'), ('C', 'Comedia'), ('E', 'Epico'), ('I', 'Infantil'), ('L', 'Literatura'), ('M', 'Matematica'), ('P', 'Poesia'), ('R', 'Romance'), ('T', 'Terror')], default='SELECIONE', max_length=1),
        ),
        migrations.AddField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(default='Sinopse..'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='static/img/VersoLivro'), upload_to=''),
        ),
    ]
